name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  test:
    permissions:
      actions: write #  to cancel/stop running workflows (styfle/cancel-workflow-action)
      contents: read #  to fetch code (actions/checkout)

    name: "JDK ${{ matrix.java }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        java: [ 21, 17 ]
        experimental: [ false ]
        # Only test on macos and windows with a single recent JDK to avoid a
        # combinatorial explosion of test configurations.
        # Most OS-specific issues are not specific to a particular JDK version.
        include:
          - os: macos-latest
            java: 21
            experimental: false
          - os: windows-latest
            java: 21
            experimental: false
          - os: ubuntu-latest
            java: 21
            experimental: false
          - os: ubuntu-latest
            java: 23
            experimental: false
          - os: ubuntu-latest
            java: EA
            experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'
      - name: 'Set up JDK 25 from jdk.java.net'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 25
          cache: 'maven'
      - name: 'Set up JDK 26 from jdk.java.net'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 26
          cache: 'maven'
      - name: 'Set up JDK ${{ matrix.java }} from jdk.java.net'
        if: ${{ matrix.java == 'EA' }}
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ matrix.java }}
          cache: 'maven'
      - name: 'Set up JDK ${{ matrix.java }}'
        if: ${{ matrix.java != 'EA' }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'
      - name: 'Install'
        shell: bash
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: 'Test'
        shell: bash
        run: mvn test -B
      - name: 'Javadoc'
        shell: bash
        run: mvn -P '!examples' javadoc:javadoc

  publish_snapshot:
    name: 'Publish snapshot'
    needs: test
    if: github.event_name == 'push' && github.repository == 'google/error-prone' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4
      - name: 'Set up JDK 25 from jdk.java.net'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 25
          cache: 'maven'
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'
          server-id: sonatype-nexus-snapshots
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD
      - name: 'Publish'
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        run: mvn source:jar deploy -B -DskipTests=true -Dinvoker.skip=true

  generate_docs:
    permissions:
      contents: write #  for git push

    name: 'Generate latest docs'
    needs: test
    if: github.event_name == 'push' && github.repository == 'google/error-prone' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4
      - name: 'Set up JDK 25 from jdk.java.net'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 25
          cache: 'maven'
      - name: 'Set up JDK 23'
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'zulu'
          cache: 'maven'
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'
      - name: 'Generate latest docs'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./util/generate-latest-docs.sh
